import LegalDocument from "../components/layout/LegalDocument";
import CompanyLegalBlock from "../components/layout/CompanyLegalBlock";
import { Link } from "react-router-dom";
import { usePageMeta } from "../hooks/usePageMeta";
import { COMPANY, SOCIAL_LINKS } from "../data/company";

const LAST_UPDATED = "June 24, 2025";

export default function Terms() {
  usePageMeta(
    "Terms & Conditions",
    "Terms governing use of Vhois AI services, platform responsibilities, and limitations of liability."
  );

  return (
    <div className="min-h-screen pt-28 sm:pt-32 pb-20">
      <div className="page-bleed">
        <LegalDocument
          title="Terms & Conditions"
          lastUpdated={LAST_UPDATED}
          sections={[
            {
              id: "acceptance",
              title: "Acceptance of terms",
              content: (
                <>
                  <p>
                    These Terms & Conditions (&quot;Terms&quot;) govern your access to and use of
                    the Vhois AI website, APIs, dashboards, pilots, and related services
                    (collectively, the &quot;Services&quot;) operated by {COMPANY.legalName} (
                    {COMPANY.domain}).
                  </p>
                  <p>
                    By accessing or using the Services, you agree to be bound by these Terms. If you
                    are using the Services on behalf of an organization, you represent that you have
                    authority to bind that organization.
                  </p>
                </>
              ),
            },
            {
              id: "use-of-services",
              title: "Use of Vhois AI services",
              content: (
                <>
                  <p>
                    Vhois provides conversation intelligence infrastructure, including speech
                    ingestion, transcription, analysis, search, audit, and related outputs. Access
                    may be subject to separate order forms, pilot agreements, or enterprise
                    contracts that supplement these Terms.
                  </p>
                  <p>
                    We may modify, suspend, or discontinue features with reasonable notice where
                    practicable. Beta or pilot features may be offered &quot;as is&quot; with
                    limited support.
                  </p>
                </>
              ),
            },
            {
              id: "user-responsibilities",
              title: "User responsibilities",
              content: (
                <>
                  <p>You agree to:</p>
                  <ul className="list-disc pl-5 space-y-2">
                    <li>Provide accurate registration and contact information</li>
                    <li>Maintain the confidentiality of account credentials</li>
                    <li>Use the Services only in compliance with applicable laws and regulations</li>
                    <li>
                      Obtain all required consents before recording, uploading, or processing
                      third-party audio or personal data
                    </li>
                    <li>Review AI-generated outputs before relying on them for critical decisions</li>
                  </ul>
                </>
              ),
            },
            {
              id: "uploaded-content",
              title: "Uploaded content and permissions",
              content: (
                <>
                  <p>
                    You retain ownership of audio, transcripts, and other content you submit
                    (&quot;Customer Content&quot;). You grant Vhois a limited license to host,
                    process, transmit, and display Customer Content solely to provide and improve
                    the Services as permitted by your agreement with us.
                  </p>
                  <p>
                    You represent that you have all rights necessary to submit Customer Content and
                    that its processing does not violate third-party rights or applicable law.
                  </p>
                </>
              ),
            },
            {
              id: "ai-disclaimer",
              title: "AI-generated outputs disclaimer",
              content: (
                <>
                  <p>
                    Outputs generated by Vhois, including transcripts, summaries, classifications,
                    scores, and recommendations, are produced by automated systems and may contain
                    errors, omissions, or misattributions. They are provided for informational and
                    operational support purposes.
                  </p>
                  <p>
                    Vhois does not provide legal, medical, financial, or compliance advice. You are
                    solely responsible for how outputs are used, including in regulated environments
                    such as legal, healthcare, or financial services.
                  </p>
                </>
              ),
            },
            {
              id: "no-misuse",
              title: "No misuse of platform",
              content: (
                <>
                  <p>You may not:</p>
                  <ul className="list-disc pl-5 space-y-2">
                    <li>Reverse engineer, scrape, or attempt to extract source models or systems</li>
                    <li>Interfere with security, availability, or integrity of the Services</li>
                    <li>Upload malware, unlawful content, or data you are not authorized to process</li>
                    <li>Use the Services to harass, surveil individuals unlawfully, or violate privacy rights</li>
                    <li>Resell or sublicense the Services without written authorization</li>
                  </ul>
                  <p>We may investigate and suspend access for suspected violations.</p>
                </>
              ),
            },
            {
              id: "intellectual-property",
              title: "Intellectual property",
              content: (
                <>
                  <p>
                    Vhois and its licensors own all rights in the Services, software, documentation,
                    branding, and underlying technology, excluding Customer Content. No rights are
                    granted except as expressly stated in these Terms or a signed agreement.
                  </p>
                  <p>
                    Feedback you provide may be used by Vhois to improve products without obligation
                    to you, unless otherwise agreed in writing.
                  </p>
                </>
              ),
            },
            {
              id: "confidentiality",
              title: "Confidentiality",
              content: (
                <p>
                  Each party may receive confidential information from the other. The receiving party
                  will use reasonable care to protect such information and use it only for purposes
                  of the relationship. Confidentiality obligations survive termination, subject to
                  standard exceptions (public domain, independent development, lawful disclosure).
                </p>
              ),
            },
            {
              id: "service-availability",
              title: "Service availability",
              content: (
                <>
                  <p>
                    We strive for high availability but do not guarantee uninterrupted or error-free
                    operation. Scheduled maintenance, third-party outages, and force majeure events
                    may affect access. Enterprise customers may have separate service level
                    commitments in their contracts.
                  </p>
                </>
              ),
            },
            {
              id: "limitation-of-liability",
              title: "Limitation of liability",
              content: (
                <>
                  <p>
                    TO THE MAXIMUM EXTENT PERMITTED BY LAW, VHOIS AND ITS AFFILIATES, OFFICERS,
                    EMPLOYEES, AND SUPPLIERS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
                    SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR
                    GOODWILL, ARISING FROM YOUR USE OF THE SERVICES.
                  </p>
                  <p>
                    OUR AGGREGATE LIABILITY FOR CLAIMS RELATING TO THE SERVICES WILL NOT EXCEED THE
                    GREATER OF (A) AMOUNTS PAID BY YOU TO VHOIS IN THE TWELVE MONTHS PRECEDING THE
                    CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS (USD $100), EXCEPT WHERE PROHIBITED BY
                    LAW.
                  </p>
                  <p>
                    Some jurisdictions do not allow certain limitations; in those cases, limitations
                    apply to the fullest extent permitted.
                  </p>
                </>
              ),
            },
            {
              id: "termination",
              title: "Termination",
              content: (
                <>
                  <p>
                    You may stop using the Services at any time. We may suspend or terminate access
                    if you breach these Terms, pose a security risk, or as required by law. Upon
                    termination, your right to use the Services ceases; provisions that by nature
                    should survive (including liability limits, IP, and confidentiality) will
                    survive.
                  </p>
                </>
              ),
            },
            {
              id: "changes",
              title: "Changes to terms",
              content: (
                <p>
                  We may update these Terms from time to time. Material changes will be posted on
                  this page with an updated &quot;Last updated&quot; date. Continued use after
                  changes constitutes acceptance. If you disagree with revised Terms, discontinue
                  use of the Services.
                </p>
              ),
            },
            {
              id: "governing-law",
              title: "Governing law",
              content: (
                <p>
                  These Terms are governed by the laws of India, without regard to conflict-of-law
                  principles. Courts located in India shall have exclusive jurisdiction over disputes
                  arising from these Terms, unless otherwise specified in a signed enterprise
                  agreement.
                </p>
              ),
            },
            {
              id: "contact",
              title: "Contact information",
              content: (
                <>
                  <p>For questions about these Terms, contact us at:</p>
                  <ul className="list-none space-y-2 mt-3">
                    <li>
                      <strong className="text-platinum/90">Email:</strong>{" "}
                      <a
                        href={`mailto:${COMPANY.email}`}
                        className="text-platinum hover:underline"
                      >
                        {COMPANY.email}
                      </a>
                    </li>
                    <li>
                      <strong className="text-platinum/90">Website:</strong>{" "}
                      <Link to="/contact" className="text-platinum hover:underline">
                        Contact form
                      </Link>
                    </li>
                    <li>
                      <strong className="text-platinum/90">LinkedIn:</strong>{" "}
                      <a
                        href={SOCIAL_LINKS.linkedin}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-platinum hover:underline"
                      >
                        Vhois AI
                      </a>
                    </li>
                  </ul>
                </>
              ),
            },
          ]}
        />
        <div className="max-w-3xl mx-auto mt-12">
          <CompanyLegalBlock />
        </div>
      </div>
    </div>
  );
}
